# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4643943686ca85a2eb6860485377b475438401480492a2d145fb2e9bf8c9516f4727dcaca6412baf4c8b45c9690f9cc59cc604c254fddb12be7e66c7e599af97

test:
  secret_key_base: 05afc03b42e46212a7afe807b8aaada9057c630c5037f43a9f578653511a384cd4f0f458ae41c5ffefa8cb230b76844812946f6eca762d8f74e09dd37f689adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
